### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by rchen8** [iguanahotsauce/Node_Skiplagged_API#3]
Followed the installation instructions but get this error when running
`node examples/get_cheapest_flight.js`

```
/Users/richard/Documents/Code/Projects/Node_Skiplagged_API/index.js:562
      for(var j=0; j<flight_data.depart.length; j++) {
                                       ^

TypeError: Cannot read property 'length' of undefined
    at IncomingMessage.<anonymous> (/Users/richard/Documents/Code/Projects/Node_Skiplagged_API/index.js:562:40)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
```

I also edited the data in `get_cheapest_flights.js` to

```
var data = {
  FROM: 'SFO',
  TO: 'DFW',
  DEPART_DATE: '2016-09-01'
};
```

**Comment by iguanahotsauce** [comment]
I will take a look into this and see what I need to do to resolve the issue.
